# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gcvtaEDCFLron_gJ2Li3wGuIZsWav8GV
"""

def get_prime_numbers(n):

    # Создаем список чисел от 2 до n и помечаем их как простые

    is_prime = [True] * (n+1)



    # Начинаем от числа 2

    p = 2

    while p * p <= n:

        # Если p помечено как простое, вычеркиваем все его кратные числа

        if is_prime[p]:

            for i in range(p * p, n+1, p):

                is_prime[i] = False

        p += 1



    # Составляем список простых чисел

    prime_numbers = []

    for i in range(2, n+1):

        if is_prime[i]:

            prime_numbers.append(i)



    return prime_numbers



# Читаем число n из ввода

n = int(input("Введите число n: "))



# Получаем список простых чисел от 1 до n

prime_numbers = get_prime_numbers(n)



# Выводим список простых чисел

print("Список простых чисел от 1 до", n, ":", prime_numbers)

N = int (input ('Введите число: '))

for d in range (1, N // 2 + 1) :
  if N % d == 0 :
    print (d, ' ', sep = '', end = '')
print (N)